### ISSUE TITLE
Connection failed in webrtc

### ISSUE THREAD

**Issue by zeyugao** [ehfd/docker-nvidia-glx-desktop#17]
I have no idea what's wrong. I can connect to webrtc but not the vnc

Run with command (from ReadMe):

```
docker run --gpus 1 -it -e TZ=UTC -e SIZEW=1920 -e SIZEH=1080 -e REFRESH=60 -e DPI=96 -e CDEPTH=24 -e VIDEO_PORT=DFP -e PASSWD=mypasswd -e WEBRTC_ENCODER=nvh264enc -e BASIC_AUTH_PASSWORD=mypasswd -p 127.0.0.1:8080:8080 ghcr.io/ehfd/nvidia-glx-desktop:latest
```

GPU is v100
Here are the logs
Some ERRORs are in entrypoint.log but I cannot determine which one is critical

[entrypoint-stdout---supervisor-bgokahf1.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/7661154/entrypoint-stdout---supervisor-bgokahf1.log)
[supervisord.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/7661155/supervisord.log)
[Xorg.0.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/7661161/Xorg.0.log)
[selkies-gstreamer-stdout---supervisor-8u_8ckmh.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/7661174/selkies-gstreamer-stdout---supervisor-8u_8ckmh.log)

**Comment by ehfd** [comment]
Sorry for the late reply. It seems that your `selkies-gstreamer-stdout---supervisor-8u_8ckmh.log` is empty other than confirmation that the X server started. The rest are okay. I would have given you prompt assistance if `selkies-gstreamer-stdout---supervisor-8u_8ckmh.log` had an error log, but since there is nothing in that log file, I would have to determine that selkies-gstreamer hadn't started at all. Could you reproduce everything after waiting sufficiently everything inside the container to start and use `htop` to check which processes are started and which are not?

**Comment by zeyugao** [comment]
I wait for a while and retry. Here are the logs.
It seems that selkies-gstreamer's log is not empty.
The process list is in ps.txt

[selkies-gstreamer-stdout---supervisor-5cd_gmr9.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/7733402/selkies-gstreamer-stdout---supervisor-5cd_gmr9.log)
[supervisord.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/7733403/supervisord.log)
[entrypoint-stdout---supervisor-bt8d_pdm.log](https://github.com/ehfd/docker-nvidia-glx-desktop/files/7733404/entrypoint-stdout---supervisor-bt8d_pdm.log)
[ps.txt](https://github.com/ehfd/docker-nvidia-glx-desktop/files/7733401/ps.txt)

And two errors in web console for webrtc. I am using ssh port forwarding `-N -L 18080:127.0.0.1:8080`
![image](https://user-images.githubusercontent.com/6374697/146508230-ebfe6796-c318-4c91-aef1-d863d978cfea.png)

**Comment by ehfd** [comment]
This is a case where you have to read [Using a TURN Server](https://github.com/ehfd/docker-nvidia-glx-desktop#using-a-turn-server), since I think you are sshing to a remote server with NAT. Please either use a public TURN instance or your on coTURN server for relaying the stream. Since selkies-gstreamer uses WebRTC, there is no workaround for this until WebTransport is a recognized standard for all web browsers.

**Comment by ehfd** [comment]
One more further note, this issue has a workaround by adding `--net=host` to the `docker run` [command](https://docs.docker.com/network/host/). For Kubernetes, add `hostNetwork: true` to the pod spec yaml file. This documentation will be updated to the README.md file with other updates.

**Comment by ehfd** [comment]
> One more further note, this issue has a workaround by adding `--net=host` to the `docker run` [command](https://docs.docker.com/network/host/). For Kubernetes, add `hostNetwork: true` to the pod spec yaml file. This documentation will be updated to the README.md file with other updates.

Documentation added in commit https://github.com/ehfd/docker-nvidia-glx-desktop/commit/aac2c25d907895391834ccab307e0e05ca0d111e.

**Comment by ehfd** [comment]
More documentation added to [Using a TURN Server](https://github.com/ehfd/docker-nvidia-glx-desktop#using-a-turn-server)
